name: reusable java build
permissions:
      id-token: write   
      contents: read    
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: soni/java-test/.github/workflows/java.yaml@main # correct 