trigger: none
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: buildanddeploy
    jobs:
      - job: joba
        steps:
         - script: echo "Hello joba"
           displayName: ' step1 execution'
  - stage: buildanddeploya
    jobs:
      - job: joba
        steps:
         - script: echo "Hello joba"
           displayName: ' step1 execution'
  - stage: buildanddeployb
    jobs:
      - job: joba
        steps:
         - script: echo "Hello joba"
           displayName: ' step1 execution'