name: Terraform remote login
on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: MY_AWS_REGION                   
 
jobs:
  aws_action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: 'workflow setup'
# Code checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# configure aws credentials for action
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
# Setup terraform CLI with TF_API_TOKEN
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # Initialize terraform
      - name: Terraform Init
        run: terraform  init 
        working-directory: Aws-project/project # this is directory where all terraform files are

# Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform  plan -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}"
        working-directory:  Aws-project
# Apply the plan if apply parameter selected during run.
      - name: Terraform Apply
        #if: ${{ github.event.inputs.TFACTION == 'apply' }}
        run: terraform  apply --auto-approve -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}"
        working-directory:  Aws-project/project
