name: Terraform pipeline for AWS
on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: MY_AWS_REGION                   
 
jobs:
  aws_action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: 'workflow setup'
# Code checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
# configure aws credentials for action
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
# Setup terraform CLI with TF_API_TOKEN
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
# Initialize terraform
      - name: Terraform Init
        run: terraform  init
        working-directory: Terraform-project/Project # this is directory where all terraform files are

# Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform  plan -input=false
        working-directory:  Terraform-project/Project
# Apply the plan if apply parameter selected during run.
      - name: Terraform Apply
        if: ${{ github.event.inputs.TFACTION == 'apply' }}
        run: terraform  apply --auto-approve -input=false
        working-directory:  Terraform-project/Project
# Destroy the infra if destroy parameter selected during run.
      - name: Terraform Destroy
        if: ${{ github.event.inputs.TFACTION == 'destroy' }}
        run: terraform destroy --auto-approve -input=false
        working-directory:  Terraform-project/Project
